title: jaehwanp
description: jaehwanp's blog
theme: just-the-docs
baseurl: ''
url: https://jaehwanp.github.io

permalink: pretty

aux_links:
  'GitHub': https://github.com/jaehwanp

color_scheme: nil
